# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Scalar-Timestamp
version:      0.01
version_from: lib/Tie/Scalar/Timestamp.pm
installdirs:  site
requires:
    POSIX:                         1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
